import * as assert from 'assert'
import { classifySlashCommand, parseCommandBlock, extractCacheRiskCommand } from '../cacheRiskCommands'
import { analyzeCacheBreaks, type CacheTurnInput } from '../shared/cacheBreak'

// ── Cache-risk slash commands read from the transcript (TRDD-EYA3X5MQ) ──────────────────────────
// Ground truth for the causes the hook layer cannot see: there is no plugin-reload hook and
// ConfigChange was measured and REFUTED, but Claude Code persists every built-in command it runs
// as a `type: "user"` entry holding a `<command-name>` block.

const RELOAD_ENTRY = {
  type: 'user',
  timestamp: '2026-07-21T11:02:02.291Z',
  sessionId: '7877ae1f-1e98-4b76-8349-7d609f1a0f02',
  message: {
    content: '<command-name>/reload-plugins</command-name>\n'
      + '            <command-message>reload-plugins</command-message>\n'
      + '            <command-args></command-args>',
  },
}

const RELOAD_STDOUT = 'Reloaded: 34 plugins · 117 skills · 75 agents · 27 hooks · 2 plugin MCP servers · 9 plugin LSP servers'

suite('cacheRiskCommands — transcript command detection (TRDD-EYA3X5MQ)', () => {
  test('classifies the always-mutating action commands as certain', () => {
    assert.deepStrictEqual(classifySlashCommand('/reload-plugins'), { kind: 'PLUGINS_RELOADED', mutation: 'certain' })
    assert.deepStrictEqual(classifySlashCommand('/reload-skills'), { kind: 'SKILLS_RELOADED', mutation: 'certain' })
    assert.deepStrictEqual(classifySlashCommand('/login'), { kind: 'ACCOUNT_SWITCHED', mutation: 'certain' })
    assert.deepStrictEqual(classifySlashCommand('/logout'), { kind: 'ACCOUNT_SWITCHED', mutation: 'certain' })
  })

  test('bare menu commands are ambiguous — opening a picker may change nothing', () => {
    assert.strictEqual(classifySlashCommand('/plugin')?.mutation, 'ambiguous')
    assert.strictEqual(classifySlashCommand('/mcp')?.mutation, 'ambiguous')
    assert.strictEqual(classifySlashCommand('/model')?.mutation, 'ambiguous')
  })

  test('/plugin with a mutating verb is certain; a non-mutating arg is not a cache risk', () => {
    assert.deepStrictEqual(classifySlashCommand('/plugin', 'update ai-maestro-janitor'),
      { kind: 'PLUGIN_CHANGED', mutation: 'certain' })
    assert.deepStrictEqual(classifySlashCommand('/plugin', 'marketplace remove shipshitdev'),
      { kind: 'PLUGIN_CHANGED', mutation: 'certain' })
    // real transcripts contain a redundant leading `plugin` — the verb must still be found
    assert.strictEqual(classifySlashCommand('/plugin', 'plugin update x@y')?.mutation, 'certain')
    assert.strictEqual(classifySlashCommand('/plugin', 'list'), undefined)
  })

  test('unrelated commands are not cache risks', () => {
    assert.strictEqual(classifySlashCommand('/help'), undefined)
    assert.strictEqual(classifySlashCommand('/janitor-resume'), undefined)
  })

  test('the command block must be ANCHORED — a message quoting the tag is not a command', () => {
    assert.ok(parseCommandBlock('<command-name>/reload-plugins</command-name>'))
    // an assistant explaining the feature, or a pasted log, must NOT register as a reload
    assert.strictEqual(parseCommandBlock('the tag is <command-name>/reload-plugins</command-name> btw'), undefined)
    assert.strictEqual(extractCacheRiskCommand({
      ...RELOAD_ENTRY,
      message: { content: 'I ran <command-name>/reload-plugins</command-name> earlier' },
    }), undefined)
  })

  test('a <local-command-caveat> preamble still anchors', () => {
    const block = parseCommandBlock(
      '<local-command-caveat>Caveat: generated by a local command.</local-command-caveat>\n'
      + '<command-name>/clear</command-name>')
    assert.strictEqual(block?.name, '/clear')
  })

  test('extracts ts/session/kind from a real reload entry', () => {
    const cmd = extractCacheRiskCommand(RELOAD_ENTRY)
    assert.strictEqual(cmd?.kind, 'PLUGINS_RELOADED')
    assert.strictEqual(cmd?.mutation, 'certain')
    assert.strictEqual(cmd?.command, '/reload-plugins')
    assert.strictEqual(cmd?.session, '7877ae1f-1e98-4b76-8349-7d609f1a0f02')
    assert.strictEqual(cmd?.ts, Date.parse('2026-07-21T11:02:02.291Z'))
  })

  // Guards the removed-catalogs decision: the `Reloaded: 34 plugins · …` line the command prints
  // into the live conversation is NOT persisted (machine-wide: 14 records hold it, none of them a
  // command entry — all quotes). A stdout that shows up in a message must therefore never be
  // treated as evidence of anything; the command block alone is the record.
  test('a trailing stdout block is ignored — the command still classifies on its own', () => {
    const cmd = extractCacheRiskCommand({
      ...RELOAD_ENTRY,
      message: { content: `<command-name>/reload-plugins</command-name>\n<local-command-stdout>${RELOAD_STDOUT}</local-command-stdout>` },
    })
    assert.strictEqual(cmd?.kind, 'PLUGINS_RELOADED')
    assert.deepStrictEqual(Object.keys(cmd ?? {}).sort(), ['command', 'kind', 'mutation', 'session', 'ts'])
  })

  test('non-user entries and array content (tool_result) never yield a command', () => {
    assert.strictEqual(extractCacheRiskCommand({ ...RELOAD_ENTRY, type: 'assistant' }), undefined)
    assert.strictEqual(extractCacheRiskCommand({
      ...RELOAD_ENTRY,
      message: { content: [{ type: 'tool_result', content: '<command-name>/reload-plugins</command-name>' }] },
    }), undefined)
  })

  test('an unparseable timestamp is dropped rather than dated to the epoch', () => {
    assert.strictEqual(extractCacheRiskCommand({ ...RELOAD_ENTRY, timestamp: 'not-a-date' }), undefined)
    assert.strictEqual(extractCacheRiskCommand({ ...RELOAD_ENTRY, timestamp: undefined }), undefined)
  })
})

// The join between the two halves: a command carries a wall-clock, a broken turn now carries one
// too (CacheBreakTurn.tsMs), and "the command is billed on the first turn at or after it" is only
// expressible if that field actually survives the analyzer.
suite('cacheBreak — tsMs is the command→turn join key (TRDD-EYA3X5MQ)', () => {
  const T1 = Date.parse('2026-07-21T11:00:00.000Z')
  const T2 = Date.parse('2026-07-21T11:02:30.000Z')
  const turns: CacheTurnInput[] = [
    { turn: 1, sources: [], inputTokens: 0, cacheReadTokens: 1000, cacheCreateTokens: 0, timestampMs: T1 },
    { turn: 2, sources: [], inputTokens: 0, cacheReadTokens: 0, cacheCreateTokens: 500_000, timestampMs: T2, model: 'b', },
  ]

  test('the emitted broken turn carries the turn wall-clock', () => {
    const broken = analyzeCacheBreaks('s1', [{ ...turns[0], model: 'a' }, turns[1]]).turns.filter(t => t.broke)
    assert.ok(broken.length >= 1, 'expected at least one broken turn')
    assert.strictEqual(broken[0].tsMs, T2)
  })

  test('a command at 11:02:02 attributes to the FIRST turn at or after it, not the one before', () => {
    const cmdTs = Date.parse('2026-07-21T11:02:02.291Z')   // the real reload from this session
    const all = analyzeCacheBreaks('s1', [{ ...turns[0], model: 'a' }, turns[1]]).turns
    const billed = all.filter(t => t.tsMs !== undefined && t.tsMs >= cmdTs)
      .sort((a, b) => (a.tsMs ?? 0) - (b.tsMs ?? 0))[0]
    assert.strictEqual(billed.turn, 2)
    assert.strictEqual(billed.wastedTokens, 500_000)
  })

  test('a turn with no timeline timestamp leaves tsMs undefined rather than inventing 0', () => {
    const noTs = analyzeCacheBreaks('s1', [
      { turn: 1, sources: [], inputTokens: 0, cacheReadTokens: 1000, cacheCreateTokens: 0, model: 'a' },
      { turn: 2, sources: [], inputTokens: 0, cacheReadTokens: 0, cacheCreateTokens: 500_000, model: 'b' },
    ]).turns.filter(t => t.broke)
    assert.strictEqual(noTs[0].tsMs, undefined)
  })
})
