// Shared token-totals strip. Dropped into tabs that otherwise show no token magnitude
// (Tools, Patterns, Flow, Agents) so a token count is visible in every tab/section — the
// answer to "no token count visible in every tab/section". It reuses tokenBreakdown() (the
// single source of truth for fresh-vs-cache input) so the "fresh input" figure here never
// re-introduces the per-turn cache-read inflation that made marathon sessions look impossibly
// large. formatCompact keeps the strip terse; the full count is in each stat's tooltip.
import { tokenBreakdown, formatCompact } from './utils'
import type { SessionSummaryCard } from './types'

function Stat({ label, value, title }: { label: string; value: string; title: string }) {
  return (
    <div title={title} style="display:flex;flex-direction:column;gap:1px;min-width:0;cursor:help">
      <span style="font-size:15px;font-weight:700;color:var(--fg);line-height:1.1">{value}</span>
      <span style="font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:0.04em">{label}</span>
    </div>
  )
}

export function TokenTotalsBar({ sessions, note }: { sessions: SessionSummaryCard[]; note?: string }) {
  const agg = sessions.reduce(
    (a, s) => {
      const b = tokenBreakdown(s)
      a.fresh += b.fresh
      a.cacheRead += b.cacheRead
      a.cacheWrite += b.cacheWrite
      a.output += b.output
      a.tools += s.totalToolCalls
      a.llm += s.totalLlmCalls
      return a
    },
    { fresh: 0, cacheRead: 0, cacheWrite: 0, output: 0, tools: 0, llm: 0 },
  )
  const n = (v: number) => v.toLocaleString()

  return (
    <div style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;padding:8px 12px;margin-bottom:14px;border:1px solid var(--border);border-radius:6px;background:var(--vscode-editorWidget-background,rgba(127,127,127,0.06))">
      <Stat label="Fresh input" value={formatCompact(agg.fresh)} title={n(agg.fresh) + ' fresh input tokens (new context sent to the model; excludes cache reads)'} />
      {agg.cacheRead > 0 && <Stat label="Cache read" value={formatCompact(agg.cacheRead)} title={n(agg.cacheRead) + ' tokens read from prompt cache (cheap; not fresh input)'} />}
      {agg.cacheWrite > 0 && <Stat label="Cache write" value={formatCompact(agg.cacheWrite)} title={n(agg.cacheWrite) + ' tokens written to prompt cache'} />}
      <Stat label="Output" value={formatCompact(agg.output)} title={n(agg.output) + ' tokens generated by the model'} />
      <Stat label="LLM calls" value={n(agg.llm)} title={n(agg.llm) + ' LLM requests across ' + sessions.length + ' session(s)'} />
      <Stat label="Tool calls" value={n(agg.tools)} title={n(agg.tools) + ' tool invocations across ' + sessions.length + ' session(s)'} />
      {note && <span style="font-size:10px;color:var(--muted);margin-left:auto;align-self:center;max-width:40%;text-align:right">{note}</span>}
    </div>
  )
}
