//! P5b parity: the library log reader (discovery → parse → finish step) against the TS oracle
//! `finishRustTranscript` (fixtures/log-reader-expected.json, generated by
//! gen-log-reader-expected.mjs from the committed fixture HOME tree) — at a HOT now (timelines
//! kept) and a COLD now (the parent loses its timeline, children keep theirs), plus the card map
//! wiring (run_cold_log_scan → put_log_session → the global timeline tier).

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use agentlens_core::log_reader::cold_scan;
use agentlens_core::CoreState;
use agentlens_logscan::discovery::{Env, Platform};
use serde_json::Value;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures")
}

fn fixture_env() -> Env {
    // Darwin roots regardless of the host: the fixture tree carries `Library/Application Support`.
    Env { home: fixtures().join("logs-home"), platform: Platform::Darwin, vars: HashMap::new() }
}

fn expected() -> Value {
    serde_json::from_str(&std::fs::read_to_string(fixtures().join("log-reader-expected.json")).unwrap()).unwrap()
}

fn cards_by_id(env: &Env, now_ms: i64) -> HashMap<String, Value> {
    let (scanned, stats) = cold_scan(env, now_ms);
    // 5 discovered files (the .json with a .jsonl sibling and the events-less copilot dir are
    // NOT sessions), every one parsed, 7 cards (claude parent + 2 children + 4 singles).
    assert_eq!((stats.files, stats.parsed, stats.cards), (5, 5, 7));
    let mut out = HashMap::new();
    for s in scanned {
        assert!(s.file_size_bytes > 0, "{}", s.file);
        for c in s.cards {
            let id = c["sessionId"].as_str().unwrap().to_owned();
            assert!(out.insert(id.clone(), c).is_none(), "duplicate card {id}");
        }
    }
    out
}

fn check(got: &HashMap<String, Value>, want: &Value, label: &str) {
    let want = want.as_object().unwrap();
    assert_eq!(got.len(), want.len(), "{label}: card count");
    for (id, w) in want {
        let g = got.get(id).unwrap_or_else(|| panic!("{label}: missing card {id}"));
        if g != w {
            let gs = serde_json::to_string_pretty(g).unwrap();
            let ws = serde_json::to_string_pretty(w).unwrap();
            for (i, (a, b)) in gs.lines().zip(ws.lines()).enumerate() {
                if a != b {
                    panic!("{label}: card {id} diverges at line {i}:\n  rust: {a}\n  ts:   {b}");
                }
            }
            panic!("{label}: card {id} diverges (length)\nrust:\n{gs}\nts:\n{ws}");
        }
    }
}

#[test]
fn finish_step_matches_the_ts_oracle_hot_and_cold() {
    let e = expected();
    let env = fixture_env();
    let hot = cards_by_id(&env, e["nowHotMs"].as_i64().unwrap());
    check(&hot, &e["hot"], "hot");
    // The mixed-speed Claude session carries the blended cost as its LAST key; the parent keeps
    // its 9 entries while hot.
    let parent = &hot["cccccccc-1111-2222-3333-444444444444"];
    assert!(parent["speedBlendedCostUsd"].as_f64().unwrap() > 0.0);
    assert_eq!(parent.as_object().unwrap().keys().last().unwrap(), "speedBlendedCostUsd");
    assert_eq!(parent["timeline"].as_array().unwrap().len(), 9);

    let cold = cards_by_id(&env, e["nowColdMs"].as_i64().unwrap());
    check(&cold, &e["cold"], "cold");
    let parent = &cold["cccccccc-1111-2222-3333-444444444444"];
    assert_eq!(parent["timeline"].as_array().unwrap().len(), 0);
    assert_eq!(parent["timelineTruncatedCount"], 9);
    assert_eq!(parent["timelineRetainedBytes"], 0);
    // Children are never hot-age stripped (TS strips only the parent).
    assert_eq!(cold["agent-abc"]["timeline"].as_array().unwrap().len(), 1);
}

#[test]
fn run_cold_log_scan_fills_the_card_map_and_the_summary_serves_it() {
    let tmp = std::env::temp_dir().join(format!("al-logreader-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let mut st = CoreState::open(&tmp);
    let v0 = st.data_version;
    let stats = st.run_cold_log_scan(&fixture_env());
    assert_eq!(stats.cards, 7);
    assert_eq!(st.log_sessions.len(), 7);
    assert!(st.data_version > v0, "put_log_session must bump data_version");
    let summary = st.session_summary(agentlens_core::now_ms() as f64);
    let ids: Vec<&str> = summary["sessions"].as_array().unwrap().iter().map(|c| c["sessionId"].as_str().unwrap()).collect();
    assert_eq!(ids.len(), 7, "{ids:?}");
    assert!(ids.contains(&"cccccccc-1111-2222-3333-444444444444") && ids.contains(&"ffffffff-1111-2222-3333-444444444444"));
    // Re-scanning upserts (same ids, no growth).
    st.run_cold_log_scan(&fixture_env());
    assert_eq!(st.log_sessions.len(), 7);
}

#[test]
fn demote_cold_timelines_keeps_only_the_k_most_recently_active() {
    let tmp = std::env::temp_dir().join(format!("al-demote-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let mut st = CoreState::open(&tmp);
    let mk = |id: &str, start: &str, dur: f64, tl: usize| {
        serde_json::json!({ "sessionId": id, "startTime": start, "durationMs": dur,
            "timeline": (0..tl).map(|i| serde_json::json!({"spanId": format!("{id}-{i}")})).collect::<Vec<_>>() })
    };
    st.put_log_session(mk("old", "2026-08-01T10:00:00.000Z", 1000.0, 3));
    st.put_log_session(mk("newest", "2026-08-01T10:00:00.000Z", 7_200_000.0, 2)); // start+duration wins
    st.put_log_session(mk("mid", "2026-08-01T11:00:00.000Z", 0.0, 4));
    st.put_log_session(mk("nostart", "", 5.0, 1)); // unparseable start → 0 → coldest
    st.demote_cold_timelines(10);
    assert_eq!(st.log_sessions["old"]["timeline"].as_array().unwrap().len(), 3, "under the cap nothing moves");
    st.demote_cold_timelines(1);
    let tl = |id: &str| st.log_sessions[id]["timeline"].as_array().unwrap().len();
    assert_eq!((tl("newest"), tl("mid"), tl("old"), tl("nostart")), (2, 0, 0, 0));
    assert_eq!(st.log_sessions["old"]["timelineTruncatedCount"], 3);
    assert_eq!(st.log_sessions["old"]["timelineRetainedBytes"], 0);
    assert!(st.log_sessions["newest"].get("timelineTruncatedCount").is_none());
    // Idempotent: a second pass finds nothing to strip and does not double-count.
    st.demote_cold_timelines(1);
    assert_eq!(st.log_sessions["old"]["timelineTruncatedCount"], 3);
}
