//! P5b parity: the library log reader (discovery → parse → finish step) against the TS oracle
//! `finishRustTranscript` (fixtures/log-reader-expected.json, generated by
//! gen-log-reader-expected.mjs from the committed fixture HOME tree) — at a HOT now (timelines
//! kept) and a COLD now (the parent loses its timeline, children keep theirs), plus the card map
//! wiring (run_cold_log_scan → put_log_session → the global timeline tier).

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use agentlens_core::log_reader::{cold_scan, LogTailer, ScannedFile};
use agentlens_core::CoreState;
use agentlens_logscan::discovery::{Env, Platform};
use serde_json::Value;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures")
}

fn fixture_env() -> Env {
    // Darwin roots regardless of the host: the fixture tree carries `Library/Application Support`.
    Env { home: fixtures().join("logs-home"), platform: Platform::Darwin, vars: HashMap::new() }
}

fn expected() -> Value {
    serde_json::from_str(&std::fs::read_to_string(fixtures().join("log-reader-expected.json")).unwrap()).unwrap()
}

fn cards_by_id(env: &Env, now_ms: i64) -> HashMap<String, Value> {
    let (scanned, stats) = cold_scan(env, now_ms);
    // 5 discovered files (the .json with a .jsonl sibling and the events-less copilot dir are
    // NOT sessions), every one parsed, 7 cards (claude parent + 2 children + 4 singles).
    assert_eq!((stats.files, stats.parsed, stats.cards), (5, 5, 7));
    let mut out = HashMap::new();
    for s in scanned {
        assert!(s.file_size_bytes > 0, "{}", s.file);
        for c in s.cards {
            let id = c["sessionId"].as_str().unwrap().to_owned();
            assert!(out.insert(id.clone(), c).is_none(), "duplicate card {id}");
        }
    }
    out
}

fn check(got: &HashMap<String, Value>, want: &Value, label: &str) {
    let want = want.as_object().unwrap();
    assert_eq!(got.len(), want.len(), "{label}: card count");
    for (id, w) in want {
        let g = got.get(id).unwrap_or_else(|| panic!("{label}: missing card {id}"));
        if g != w {
            let gs = serde_json::to_string_pretty(g).unwrap();
            let ws = serde_json::to_string_pretty(w).unwrap();
            for (i, (a, b)) in gs.lines().zip(ws.lines()).enumerate() {
                if a != b {
                    panic!("{label}: card {id} diverges at line {i}:\n  rust: {a}\n  ts:   {b}");
                }
            }
            panic!("{label}: card {id} diverges (length)\nrust:\n{gs}\nts:\n{ws}");
        }
    }
}

#[test]
fn finish_step_matches_the_ts_oracle_hot_and_cold() {
    let e = expected();
    let env = fixture_env();
    let hot = cards_by_id(&env, e["nowHotMs"].as_i64().unwrap());
    check(&hot, &e["hot"], "hot");
    // The mixed-speed Claude session carries the blended cost as its LAST key; the parent keeps
    // its 9 entries while hot.
    let parent = &hot["cccccccc-1111-2222-3333-444444444444"];
    assert!(parent["speedBlendedCostUsd"].as_f64().unwrap() > 0.0);
    assert_eq!(parent.as_object().unwrap().keys().last().unwrap(), "speedBlendedCostUsd");
    assert_eq!(parent["timeline"].as_array().unwrap().len(), 9);

    let cold = cards_by_id(&env, e["nowColdMs"].as_i64().unwrap());
    check(&cold, &e["cold"], "cold");
    let parent = &cold["cccccccc-1111-2222-3333-444444444444"];
    assert_eq!(parent["timeline"].as_array().unwrap().len(), 0);
    assert_eq!(parent["timelineTruncatedCount"], 9);
    assert_eq!(parent["timelineRetainedBytes"], 0);
    // Children are never hot-age stripped (TS strips only the parent).
    assert_eq!(cold["agent-abc"]["timeline"].as_array().unwrap().len(), 1);
}

#[test]
fn run_cold_log_scan_fills_the_card_map_and_the_summary_serves_it() {
    let tmp = std::env::temp_dir().join(format!("al-logreader-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let mut st = CoreState::open(&tmp);
    let v0 = st.data_version;
    let (scanned, stats) = cold_scan(&fixture_env(), agentlens_core::now_ms());
    assert_eq!(stats.cards, 7);
    st.ingest_scanned(scanned);
    assert_eq!(st.log_sessions.len(), 7);
    assert!(st.data_version > v0, "put_log_session must bump data_version");
    let summary = st.session_summary(agentlens_core::now_ms() as f64);
    let ids: Vec<&str> = summary["sessions"].as_array().unwrap().iter().map(|c| c["sessionId"].as_str().unwrap()).collect();
    assert_eq!(ids.len(), 7, "{ids:?}");
    assert!(ids.contains(&"cccccccc-1111-2222-3333-444444444444") && ids.contains(&"ffffffff-1111-2222-3333-444444444444"));
    // Re-ingesting upserts (same ids, no growth); an empty sweep is a no-op.
    let v1 = st.data_version;
    st.ingest_scanned(cold_scan(&fixture_env(), agentlens_core::now_ms()).0);
    assert_eq!(st.log_sessions.len(), 7);
    assert!(st.data_version > v1);
    let v2 = st.data_version;
    st.ingest_scanned(Vec::new());
    assert_eq!(st.data_version, v2, "an empty sweep must not bump data_version");
}

// ── The incremental tailer (P5d) ─────────────────────────────────────────────────────────────

/// A private copy of the fixture tree the test can append to.
fn scratch_home(name: &str) -> PathBuf {
    let dst = std::env::temp_dir().join(format!("al-tail-{}-{name}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dst);
    copy_tree(&fixtures().join("logs-home"), &dst);
    dst
}

fn copy_tree(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).unwrap();
    for e in std::fs::read_dir(src).unwrap().flatten() {
        let p = e.path();
        let to = dst.join(e.file_name());
        if p.is_dir() { copy_tree(&p, &to) } else { std::fs::copy(&p, &to).unwrap(); }
    }
}

const CLAUDE_REL: &str = ".claude/projects/-Users-someone-proj/cccccccc-1111-2222-3333-444444444444.jsonl";

fn append(path: &Path, text: &str) {
    use std::io::Write;
    let mut f = std::fs::OpenOptions::new().append(true).open(path).unwrap();
    f.write_all(text.as_bytes()).unwrap();
}

fn turn_line(id: u32, ts: &str) -> String {
    format!(
        r#"{{"type":"assistant","timestamp":"{ts}","message":{{"id":"msg_x{id}","model":"claude-opus-5","usage":{{"input_tokens":7,"output_tokens":1,"cache_read_input_tokens":0,"cache_creation_input_tokens":0}},"content":[{{"type":"text","text":"more {id}"}}]}}}}"#
    ) + "\n"
}

fn parent_card(scanned: &[ScannedFile]) -> &Value {
    scanned.iter().flat_map(|s| &s.cards).find(|c| c["sessionId"] == "cccccccc-1111-2222-3333-444444444444").expect("parent card")
}

#[test]
fn tailer_gates_on_stat_and_tails_growth_incrementally() {
    let home = scratch_home("grow");
    let env = Env { home: home.clone(), platform: Platform::Darwin, vars: HashMap::new() };
    let claude = home.join(CLAUDE_REL);
    let now = 1_785_578_400_000 + 600_000; // the fixture's HOT now
    let mut t = LogTailer::default();

    // Boot: the parallel cold path, every file from 0, state seeded.
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.files, s.changed, s.parsed, s.cards, s.incremental_reads, s.full_reads), (5, 5, 5, 7, 0, 5));
    let turns0 = parent_card(&scanned)["turns"].as_u64().unwrap();
    assert_eq!(t.file_state.len(), 5);
    let st0 = t.file_state[&claude];
    assert_eq!(st0.bytes_read, std::fs::metadata(&claude).unwrap().len());

    // Nothing moved → nothing touched.
    let (scanned, s) = t.sweep(&env, now);
    assert!(scanned.is_empty());
    assert_eq!((s.files, s.changed, s.parsed, s.incremental_reads, s.full_reads), (5, 0, 0, 0, 0));

    // Growth after a cold parse: no accumulator is cached for it → ONE from-0 read (which caches
    // the accumulator), only that file is re-parsed, and the card grew by one turn.
    append(&claude, &turn_line(1, "2026-08-01T10:00:08.000Z"));
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.parsed, s.incremental_reads, s.full_reads), (1, 1, 0, 1));
    assert_eq!(scanned.len(), 1);
    assert_eq!(parent_card(&scanned)["turns"], turns0 + 1);
    assert_eq!(t.file_state[&claude].bytes_read, std::fs::metadata(&claude).unwrap().len());

    // Growth again: the accumulator is cached → an INCREMENTAL read, and the tailed card equals
    // a from-0 parse of the same bytes field for field.
    append(&claude, &turn_line(2, "2026-08-01T10:00:09.000Z"));
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.parsed, s.incremental_reads, s.full_reads), (1, 1, 1, 0));
    let tailed = parent_card(&scanned).clone();
    assert_eq!(tailed["turns"], turns0 + 2);
    let (cold, _) = cold_scan(&env, now);
    let from_zero = parent_card(&cold);
    assert_eq!(&tailed, from_zero, "incremental tail diverged from a from-0 parse");

    // A trailing PARTIAL line is not consumed: the offset stops before it, the entry is absent,
    // and completing the line on the next sweep resumes from that offset and includes it.
    let line = turn_line(3, "2026-08-01T10:00:10.000Z");
    let (head, tail) = line.split_at(line.len() / 2);
    append(&claude, head);
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.incremental_reads), (1, 1));
    assert_eq!(parent_card(&scanned)["turns"], turns0 + 2, "a partial line must not become an entry");
    assert_eq!(t.file_state[&claude].bytes_read + head.len() as u64, std::fs::metadata(&claude).unwrap().len());
    append(&claude, tail);
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.incremental_reads), (1, 1));
    assert_eq!(parent_card(&scanned)["turns"], turns0 + 3);

    // A SHRUNK file (truncate/rotate) is never resumed from a stale offset: from 0 again.
    let body = std::fs::read_to_string(&claude).unwrap();
    let shorter: String = body.lines().take(6).map(|l| format!("{l}\n")).collect();
    std::fs::write(&claude, shorter).unwrap();
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.incremental_reads, s.full_reads), (1, 0, 1));
    let (cold, _) = cold_scan(&env, now);
    assert_eq!(parent_card(&scanned), parent_card(&cold));
    assert!(parent_card(&scanned)["turns"].as_u64().unwrap() < turns0 + 3);

    // Codex files take the same path; Copilot ones are whole-file re-reads on change.
    let codex = home.join(".codex/sessions/2026/08/01/ffffffff-1111-2222-3333-444444444444.jsonl");
    append(&codex, "{\"timestamp\":\"2026-08-01T10:00:04.000Z\",\"type\":\"event_msg\",\"payload\":{\"type\":\"token_count\",\"info\":{\"total_token_usage\":{\"input_tokens\":3000,\"cached_input_tokens\":900,\"output_tokens\":130,\"reasoning_output_tokens\":60},\"last_token_usage\":{\"input_tokens\":500}}}}\n");
    let cp = home.join(".copilot/session-state/abababab-1111-2222-3333-444444444444/events.jsonl");
    append(&cp, "{\"timestamp\":\"2026-08-01T10:00:05.000Z\",\"type\":\"assistant.message\",\"data\":{\"outputTokens\":9}}\n");
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.parsed, s.full_reads), (2, 2, 2));
    let ids: Vec<&str> = scanned.iter().flat_map(|x| &x.cards).map(|c| c["sessionId"].as_str().unwrap()).collect();
    assert_eq!(ids, vec!["ffffffff-1111-2222-3333-444444444444", "abababab-1111-2222-3333-444444444444"]);
    let (cold, _) = cold_scan(&env, now);
    for c in scanned.iter().flat_map(|x| &x.cards) {
        let from_zero = cold.iter().flat_map(|x| &x.cards).find(|d| d["sessionId"] == c["sessionId"]).unwrap();
        assert_eq!(c, from_zero);
    }
    // Codex now has a cached accumulator: the next growth tails.
    append(&codex, "{\"timestamp\":\"2026-08-01T10:00:06.000Z\",\"type\":\"event_msg\",\"payload\":{\"type\":\"token_count\",\"info\":{\"total_token_usage\":{\"input_tokens\":3100,\"cached_input_tokens\":900,\"output_tokens\":131,\"reasoning_output_tokens\":60},\"last_token_usage\":{\"input_tokens\":100}}}}\n");
    let (scanned, s) = t.sweep(&env, now);
    assert_eq!((s.changed, s.incremental_reads, s.full_reads), (1, 1, 0));
    let (cold, _) = cold_scan(&env, now);
    let codex_id = "ffffffff-1111-2222-3333-444444444444";
    let got = scanned.iter().flat_map(|x| &x.cards).find(|c| c["sessionId"] == codex_id).unwrap();
    let want = cold.iter().flat_map(|x| &x.cards).find(|c| c["sessionId"] == codex_id).unwrap();
    assert_eq!(got, want);
}

#[test]
fn demote_cold_timelines_keeps_only_the_k_most_recently_active() {
    let tmp = std::env::temp_dir().join(format!("al-demote-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    let mut st = CoreState::open(&tmp);
    let mk = |id: &str, start: &str, dur: f64, tl: usize| {
        serde_json::json!({ "sessionId": id, "startTime": start, "durationMs": dur,
            "timeline": (0..tl).map(|i| serde_json::json!({"spanId": format!("{id}-{i}")})).collect::<Vec<_>>() })
    };
    st.put_log_session(mk("old", "2026-08-01T10:00:00.000Z", 1000.0, 3));
    st.put_log_session(mk("newest", "2026-08-01T10:00:00.000Z", 7_200_000.0, 2)); // start+duration wins
    st.put_log_session(mk("mid", "2026-08-01T11:00:00.000Z", 0.0, 4));
    st.put_log_session(mk("nostart", "", 5.0, 1)); // unparseable start → 0 → coldest
    st.demote_cold_timelines(10);
    assert_eq!(st.log_sessions["old"]["timeline"].as_array().unwrap().len(), 3, "under the cap nothing moves");
    st.demote_cold_timelines(1);
    let tl = |id: &str| st.log_sessions[id]["timeline"].as_array().unwrap().len();
    assert_eq!((tl("newest"), tl("mid"), tl("old"), tl("nostart")), (2, 0, 0, 0));
    assert_eq!(st.log_sessions["old"]["timelineTruncatedCount"], 3);
    assert_eq!(st.log_sessions["old"]["timelineRetainedBytes"], 0);
    assert!(st.log_sessions["newest"].get("timelineTruncatedCount").is_none());
    // Idempotent: a second pass finds nothing to strip and does not double-count.
    st.demote_cold_timelines(1);
    assert_eq!(st.log_sessions["old"]["timelineTruncatedCount"], 3);
}
